"""Projects the compiled product registry into the Peripheral runtime.

    python -m aula_kb_v3.emit_peripheral_catalog <peripheral-worktree-root>

Two outputs, from one source of truth (`registry_data.py`, itself generated by
`compile_registry.py`):

1. `crates/pproto/src/aula_bytech_catalog.rs` -- the Rust catalogue the desktop
   app resolves a connected board against.
2. `data/devices/aula-bytech-catalog.json` -- the same facts as data, for
   anything that wants them without linking the runtime.

What deliberately does NOT cross this boundary: the research corpus. No vendor
executables, no decompiled sources, no raw opcode catalogue, no unreviewed
hypotheses. The projection carries identity bindings, layouts, capability
declarations with their evidence tier, firmware notes and validation state --
the facts a product surface is built from -- and nothing that would let a
consumer reconstruct an unreviewed command.

Determinism: the output is a pure function of `registry_data.py`. Re-running it
without changing that file must produce a byte-identical result, which is what
`tests/aula_kb_v3/test_projection_is_deterministic.py` checks.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from . import registry_data as data
from .contract import ConfidenceTier, ConnectionType

# The evidence tier names Peripheral's `pcaps::EvidenceTier` uses. Spelled out
# rather than derived from the enum's `.value` so that renaming one on either
# side is a visible edit here rather than a silent mismatch.
TIER_RUST = {
    ConfidenceTier.STATIC_ONLY: "StaticOnly",
    ConfidenceTier.INHERITED_UNCONFIRMED: "InheritedUnconfirmed",
    ConfidenceTier.LIVE_CONFIRMED: "LiveConfirmed",
    ConfidenceTier.FAMILY_VALIDATED_PHYSICAL: "FamilyValidatedPhysical",
    ConfidenceTier.PHYSICAL_VALIDATED: "PhysicalValidated",
}

# The family's capability vocabulary, in the order the Rust enum declares it.
CAPABILITY_RUST = {
    "remap": "Remap",
    "macro_definition_content": "MacroDefinitionContent",
    "macro_key_assignment": "MacroKeyAssignment",
    "actuation": "Actuation",
    "rapid_trigger": "RapidTrigger",
    "deadzone": "Deadzone",
    "profiles": "Profiles",
    "rgb_core": "RgbCore",
    "rgb_per_key": "RgbPerKey",
    "rgb_advanced": "RgbAdvanced",
    "polling": "Polling",
    "device_settings": "DeviceSettings",
    "auto_calibrate_enable": "AutoCalibrateEnable",
    "full_he_calibration": "FullHeCalibration",
    "advanced_keys_dks": "AdvancedKeysDks",
}

# The one product this project physically owns. Everything below that is a
# per-product claim rather than a family one is gated on this list, and the list
# is one line long on purpose: it is the difference between "the family works"
# and "this board works", and lengthening it needs a board in somebody's hands.
PHYSICALLY_OWNED_MODEL_IDS = {18691697672197}


def _os_mode(os_type: str) -> str:
    return {"WIN": "Windows", "MAC": "Mac"}[os_type]


def _connection(connection: ConnectionType) -> str:
    return {ConnectionType.WIRED: "Wired", ConnectionType.WIRELESS: "Wireless"}[connection]


def _rust_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _product_rows() -> list[dict]:
    rows = []
    for product in data.PRODUCTS:
        owned = product.uuid in PHYSICALLY_OWNED_MODEL_IDS
        layers = []
        quirks: list[str] = []
        for layer in product.layers:
            raw = [k.pos for k in layer.keys]
            positions = sorted(set(raw))
            if len(positions) != len(raw):
                # Not silently repaired: the vendor's own layout data lists a
                # position more than once on this layer, and a projection that
                # dropped the duplicate without saying so would hide a defect in
                # the source it claims to be faithful to. A position set is a
                # set, so the duplicate cannot survive into the runtime -- but it
                # is recorded on the product as a quirk.
                repeated = sorted({p for p in raw if raw.count(p) > 1})
                quirks.append(
                    f"vendor layout data lists position(s) "
                    f"{', '.join(str(p) for p in repeated)} more than once on layer "
                    f"{layer.layer_index}/{layer.os_type}; deduplicated when projecting"
                )
            layers.append(
                {
                    "layer_index": layer.layer_index,
                    "os_mode": _os_mode(layer.os_type),
                    "name": layer.name,
                    "positions": positions,
                }
            )
        # Collapse the same quirk repeated across layers into one line per kind.
        quirks = sorted(set(quirks))
        # Labels come from the layer a person reads a keyboard by: the Windows
        # default layer. The other layers carry the same physical keys with
        # different bindings, so a second copy of the labels would be the same
        # list with a different chance of drifting.
        label_layer = product.layer(0, "WIN") or product.layers[0]
        labels = [(k.pos, k.name) for k in sorted(label_layer.keys, key=lambda k: k.pos)]
        rows.append(
            {
                "model_id": product.uuid,
                "display_name": product.display_name,
                "vendor_id": product.vendor_id,
                "product_id": product.product_id,
                "icon": product.product_icon,
                "connection": _connection(product.connection_type),
                "identity_evidence": TIER_RUST[product.identity_confidence],
                "firmware_note": product.firmware_revision_note,
                "quirks": quirks,
                "layers": layers,
                "labels": labels,
                "capabilities": [
                    {
                        "capability": CAPABILITY_RUST[c.name],
                        "present": c.supported,
                        "evidence": TIER_RUST[c.confidence],
                    }
                    for c in product.capabilities
                ],
                "validation": {
                    # The family's own semantics were established on real
                    # hardware once, and that fact is about the family.
                    "family_hardware_verified": True,
                    # A uuid resolving to a name is the vendor's catalogue until
                    # a board answers with it here.
                    "product_binding_verified": owned,
                    # Layouts are the vendor's own per-product data, not a
                    # neighbour's, for every row.
                    "product_layout_verified": bool(product.layers),
                    # Most rows carry `inherited_unconfirmed` capabilities, which
                    # is precisely not a per-product claim.
                    "product_caps_verified": owned,
                },
            }
        )
    return rows


def emit_rust(rows: list[dict]) -> str:
    out: list[str] = []
    w = out.append
    w("//! The `aula-bytech` product catalogue: 15 keyboards, one family.")
    w("//!")
    w("//! **Generated. Do not hand-edit.** Regenerate from the research tree with")
    w("//! `python -m aula_kb_v3.emit_peripheral_catalog <peripheral-worktree>`;")
    w("//! the source of truth is that tree's `aula_kb_v3/registry_data.py`, which")
    w("//! is itself compiled from the vendor's own product catalogue and layout")
    w("//! data.")
    w("//!")
    w("//! # What this table is, and what it is not")
    w("//!")
    w("//! It is the **product** axis: which board a model id names, what keys that")
    w("//! board has, which capabilities its hardware declares, and how well each")
    w("//! of those is established. It authorises nothing. Whether a command may")
    w("//! be sent is decided by `data/protocols/aula-bytech.toml` and `psafety`,")
    w("//! per family, and nothing here can widen that.")
    w("//!")
    w("//! # Why the facts are normalised this way")
    w("//!")
    w("//! Protocol semantics are a property of the family and appear exactly once,")
    w("//! in the ACL and in this crate's engines. What varies per product is")
    w("//! identity, layout, which capabilities the hardware has, and how well each")
    w("//! is evidenced -- and only those appear below. Fifteen copies of the same")
    w("//! frame format would be fifteen chances for one of them to drift.")
    w("//!")
    w("//! # The evidence tiers are not decoration")
    w("//!")
    w("//! One board in this table has been physically touched by this project. The")
    w("//! other fourteen carry [`pcaps::EvidenceTier::LiveConfirmed`] or weaker on")
    w("//! their per-product claims, and [`ProductValidation`] keeps the four")
    w("//! separate verification states apart so that a family result cannot be")
    w("//! read as a product result.")
    w("")
    w("use pcaps::{CoreCapability, EvidenceTier, ProductValidation};")
    w("")
    w("use crate::aula_bytech::VendorModelId;")
    w("")
    w("/// Which OS-mode bank a layer belongs to.")
    w("///")
    w("/// Not a boolean: the wire encodes it as a 3-bit field alongside the layer")
    w("/// index, and two of this family's products have a *different number of")
    w("/// keys* per bank (HERO 99/99 HE: 101 on Windows, 84 on Mac), so the two")
    w("/// banks are not two views of one layout.")
    w("#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]")
    w("pub enum OsMode {")
    w("    Windows,")
    w("    Mac,")
    w("}")
    w("")
    w("impl OsMode {")
    w("    pub fn as_str(self) -> &'static str {")
    w("        match self {")
    w("            OsMode::Windows => \"WIN\",")
    w("            OsMode::Mac => \"MAC\",")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("/// How a product attaches.")
    w("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    w("pub enum Connection {")
    w("    Wired,")
    w("    Wireless,")
    w("}")
    w("")
    w("impl Connection {")
    w("    pub fn as_str(self) -> &'static str {")
    w("        match self {")
    w("            Connection::Wired => \"wired\",")
    w("            Connection::Wireless => \"wireless\",")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("/// One layer of one product, and the key positions it addresses.")
    w("///")
    w("/// `positions` is the whole point: a layout is a set of `u16` positions per")
    w("/// layer, not a key count. A count cannot answer \"is 0x5F a key on this")
    w("/// board\", which is the only question a bounds check actually asks, and")
    w("/// this family's positions are not contiguous (HERO 100's media keys sit at")
    w("/// 1024/1280/2048/2304, far above the main block).")
    w("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    w("pub struct LayerLayout {")
    w("    pub layer_index: u8,")
    w("    pub os_mode: OsMode,")
    w("    pub name: &'static str,")
    w("    pub positions: &'static [u16],")
    w("}")
    w("")
    w("/// What a key at one position is called, for a screen that has to name it.")
    w("///")
    w("/// Taken from the Windows default layer only. The other layers carry the")
    w("/// same physical keys with different bindings, so a per-layer copy would be")
    w("/// the same list with an extra chance of drifting.")
    w("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    w("pub struct KeyLabel {")
    w("    pub position: u16,")
    w("    pub label: &'static str,")
    w("}")
    w("")
    w("/// A capability in the family's own vocabulary.")
    w("///")
    w("/// Deliberately finer-grained than [`pcaps::CoreCapability`]: the vendor's")
    w("/// data distinguishes a macro's *content* from a key's *binding to* one, and")
    w("/// three separate lighting capabilities, and flattening those into the")
    w("/// generic surface would throw away the distinction the vendor's own catalogue")
    w("/// makes. [`FamilyCapability::core`] maps back where a mapping exists.")
    w("#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]")
    w("pub enum FamilyCapability {")
    for name in CAPABILITY_RUST.values():
        w(f"    {name},")
    w("}")
    w("")
    w("impl FamilyCapability {")
    w("    pub fn as_str(self) -> &'static str {")
    w("        match self {")
    for source, name in CAPABILITY_RUST.items():
        w(f"            FamilyCapability::{name} => {_rust_str(source)},")
    w("        }")
    w("    }")
    w("")
    w("    /// The generic surface item this contributes to, if any.")
    w("    ///")
    w("    /// `None` is the honest answer for the advanced and lighting variants")
    w("    /// that no rank depends on -- see [`pcaps::OptionalCapability`]. Note")
    w("    /// that two variants map to [`CoreCapability::Macro`]: uploading a macro")
    w("    /// and binding a key to one are separate hardware capabilities and both")
    w("    /// are needed before the generic item is satisfied.")
    w("    pub fn core(self) -> Option<CoreCapability> {")
    w("        match self {")
    w("            FamilyCapability::Remap => Some(CoreCapability::Remap),")
    w("            FamilyCapability::MacroDefinitionContent | FamilyCapability::MacroKeyAssignment => {")
    w("                Some(CoreCapability::Macro)")
    w("            }")
    w("            FamilyCapability::Actuation => Some(CoreCapability::HeActuation),")
    w("            FamilyCapability::RapidTrigger => Some(CoreCapability::HeRapidTrigger),")
    w("            FamilyCapability::Deadzone => Some(CoreCapability::HeDeadzone),")
    w("            FamilyCapability::Profiles => Some(CoreCapability::Profiles),")
    w("            FamilyCapability::RgbCore => Some(CoreCapability::Rgb),")
    w("            FamilyCapability::Polling => Some(CoreCapability::Polling),")
    w("            FamilyCapability::DeviceSettings => Some(CoreCapability::DeviceSettings),")
    w("            FamilyCapability::RgbPerKey")
    w("            | FamilyCapability::RgbAdvanced")
    w("            | FamilyCapability::AutoCalibrateEnable")
    w("            | FamilyCapability::FullHeCalibration")
    w("            | FamilyCapability::AdvancedKeysDks => None,")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("/// One product's claim about one capability.")
    w("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    w("pub struct ProductCapability {")
    w("    pub capability: FamilyCapability,")
    w("    /// Whether the hardware has it. Says nothing about whether this project")
    w("    /// can reach it -- that is the ACL's question.")
    w("    pub present: bool,")
    w("    pub evidence: EvidenceTier,")
    w("}")
    w("")
    w("/// One catalogued keyboard.")
    w("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    w("pub struct CatalogProduct {")
    w("    /// The value `read_model_id` answers with. The authoritative")
    w("    /// discriminator: 14 of these 15 rows share one VID/PID.")
    w("    pub model_id: u64,")
    w("    pub display_name: &'static str,")
    w("    pub vendor_id: u16,")
    w("    pub product_id: u16,")
    w("    /// The vendor's own artwork key. Carried because it is the only field")
    w("    /// that distinguishes some rows in the vendor's data, and because three")
    w("    /// products sharing one icon is itself evidence they share a firmware.")
    w("    pub icon: &'static str,")
    w("    pub connection: Connection,")
    w("    pub identity_evidence: EvidenceTier,")
    w("    pub layers: &'static [LayerLayout],")
    w("    pub labels: &'static [KeyLabel],")
    w("    pub capabilities: &'static [ProductCapability],")
    w("    /// A product-specific caveat, empty when there is none. Not free text")
    w("    /// for notes in general: it holds the reasons a row cannot be treated as")
    w("    /// interchangeable with a similar-looking one.")
    w("    pub firmware_note: &'static str,")
    w("    /// Defects and oddities found in the vendor's own product data while")
    w("    /// projecting it, one line each.")
    w("    ///")
    w("    /// Recorded rather than repaired in silence. A generated table that")
    w("    /// quietly cleaned up its source would be a table nobody could check")
    w("    /// against that source, and \"the input was wrong here\" is exactly the")
    w("    /// kind of fact a later reader needs and cannot re-derive.")
    w("    pub quirks: &'static [&'static str],")
    w("    pub validation: ProductValidation,")
    w("}")
    w("")
    w("impl CatalogProduct {")
    w("    /// The positions this product addresses on one layer and OS bank.")
    w("    ///")
    w("    /// `None` rather than an empty slice for a layer that does not exist: a")
    w("    /// board with no Mac bank and a board whose Mac bank has no keys are")
    w("    /// different claims, and only one of them is true of anything here.")
    w("    pub fn positions(&self, layer_index: u8, os_mode: OsMode) -> Option<&'static [u16]> {")
    w("        self.layers")
    w("            .iter()")
    w("            .find(|layer| layer.layer_index == layer_index && layer.os_mode == os_mode)")
    w("            .map(|layer| layer.positions)")
    w("    }")
    w("")
    w("    /// Whether `position` is a key on this product, on that layer and bank.")
    w("    pub fn addresses(&self, position: u16, layer_index: u8, os_mode: OsMode) -> bool {")
    w("        self.positions(layer_index, os_mode)")
    w("            .is_some_and(|positions| positions.binary_search(&position).is_ok())")
    w("    }")
    w("")
    w("    pub fn label(&self, position: u16) -> Option<&'static str> {")
    w("        self.labels")
    w("            .iter()")
    w("            .find(|key| key.position == position)")
    w("            .map(|key| key.label)")
    w("    }")
    w("")
    w("    pub fn capability(&self, capability: FamilyCapability) -> Option<ProductCapability> {")
    w("        self.capabilities")
    w("            .iter()")
    w("            .copied()")
    w("            .find(|entry| entry.capability == capability)")
    w("    }")
    w("")
    w("    /// Whether the hardware declares this capability at all.")
    w("    pub fn declares(&self, capability: FamilyCapability) -> bool {")
    w("        self.capability(capability)")
    w("            .is_some_and(|entry| entry.present)")
    w("    }")
    w("}")
    w("")

    # --- the position tables -------------------------------------------------
    w("// --- layouts -----------------------------------------------------------------")
    w("//")
    w("// One `const` per distinct position set. Shared where products share a set,")
    w("// which is not a size optimisation: it makes \"these two boards have the same")
    w("// key positions\" a fact the compiler enforces rather than one that happens to")
    w("// be true of two hand-copied lists.")
    w("")

    position_consts: dict[tuple[int, ...], str] = {}
    for row in rows:
        for layer in row["layers"]:
            key = tuple(layer["positions"])
            if key not in position_consts:
                position_consts[key] = f"POSITIONS_{len(position_consts):02}"
    for positions, const in position_consts.items():
        w(f"/// {len(positions)} positions.")
        w(f"const {const}: &[u16] = &[")
        line = "    "
        for value in positions:
            piece = f"{value}, "
            if len(line) + len(piece) > 96:
                w(line.rstrip())
                line = "    "
            line += piece
        if line.strip():
            w(line.rstrip())
        w("];")
        w("")

    # --- per-product statics -------------------------------------------------
    for index, row in enumerate(rows):
        slug = f"P{index:02}"
        w(f"// --- {row['display_name']} ({row['model_id']}) " + "-" * max(0, 40 - len(row["display_name"])))
        w(f"const {slug}_LAYERS: &[LayerLayout] = &[")
        for layer in row["layers"]:
            const = position_consts[tuple(layer["positions"])]
            w(
                f"    LayerLayout {{ layer_index: {layer['layer_index']}, "
                f"os_mode: OsMode::{layer['os_mode']}, name: {_rust_str(layer['name'])}, "
                f"positions: {const} }},"
            )
        w("];")
        w(f"const {slug}_LABELS: &[KeyLabel] = &[")
        line = "    "
        for position, label in row["labels"]:
            piece = f"KeyLabel {{ position: {position}, label: {_rust_str(label)} }}, "
            if len(line) + len(piece) > 100:
                w(line.rstrip())
                line = "    "
            line += piece
        if line.strip():
            w(line.rstrip())
        w("];")
        w(f"const {slug}_QUIRKS: &[&str] = &[")
        for quirk in row["quirks"]:
            w(f"    {_rust_str(quirk)},")
        w("];")
        w(f"const {slug}_CAPS: &[ProductCapability] = &[")
        for cap in row["capabilities"]:
            w(
                f"    ProductCapability {{ capability: FamilyCapability::{cap['capability']}, "
                f"present: {'true' if cap['present'] else 'false'}, "
                f"evidence: EvidenceTier::{cap['evidence']} }},"
            )
        w("];")
        w("")

    w("/// Every catalogued product, in the vendor catalogue's own order.")
    w("pub const PRODUCTS: &[CatalogProduct] = &[")
    for index, row in enumerate(rows):
        slug = f"P{index:02}"
        v = row["validation"]
        w("    CatalogProduct {")
        w(f"        model_id: {row['model_id']},")
        w(f"        display_name: {_rust_str(row['display_name'])},")
        w(f"        vendor_id: {row['vendor_id']:#06x},")
        w(f"        product_id: {row['product_id']:#06x},")
        w(f"        icon: {_rust_str(row['icon'])},")
        w(f"        connection: Connection::{row['connection']},")
        w(f"        identity_evidence: EvidenceTier::{row['identity_evidence']},")
        w(f"        layers: {slug}_LAYERS,")
        w(f"        labels: {slug}_LABELS,")
        w(f"        capabilities: {slug}_CAPS,")
        w(f"        firmware_note: {_rust_str(row['firmware_note'])},")
        w(f"        quirks: {slug}_QUIRKS,")
        w("        validation: ProductValidation {")
        for field in (
            "family_hardware_verified",
            "product_binding_verified",
            "product_layout_verified",
            "product_caps_verified",
        ):
            w(f"            {field}: {'true' if v[field] else 'false'},")
        w("        },")
        w("    },")
    w("];")
    w("")
    w("/// Resolves a `read_model_id` answer to its catalogue row.")
    w("///")
    w("/// `None` for anything not in the table -- a model this research has not")
    w("/// catalogued, which must be treated as unsupported for anything beyond the")
    w("/// read that already identified it as `aula-bytech`. Never guess from a")
    w("/// neighbour: two rows in this table share a display name and are different")
    w("/// products.")
    w("pub fn product_for(model_id: VendorModelId) -> Option<&'static CatalogProduct> {")
    w("    PRODUCTS.iter().find(|p| p.model_id == model_id.raw())")
    w("}")
    return "\n".join(out) + "\n"


def emit_json(rows: list[dict]) -> str:
    document = {
        "schema": "peripheral.product-catalog/1",
        "family": data.FAMILY.family_key,
        "generated_by": "aula_kb_v3.emit_peripheral_catalog",
        "family_spec": {
            "controller_class": data.FAMILY.controller_class,
            "report_id_tx": data.FAMILY.report_id_tx,
            "report_id_rx": data.FAMILY.report_id_rx,
            "report_id_io_rx": data.FAMILY.report_id_io_rx,
            "send_payload_length": data.FAMILY.send_payload_length,
        },
        "bounds": {
            "profile_slot_count": data.PROFILE_SLOT_COUNT,
            "actuation_bound_mm": list(data.ACTUATION_BOUND_MM),
            "actuation_gridline_mm": data.ACTUATION_GRIDLINE_MM,
            "macro_table_max_bytes": data.MACRO_TABLE_MAX_BYTES,
            "macro_event_duration_max_ms": data.MACRO_EVENT_DURATION_MAX_MS,
            "macro_name_max_utf8_bytes": data.MACRO_NAME_MAX_UTF8_BYTES,
            "polling_enum_hz": {str(k): v for k, v in sorted(data.POLLING_ENUM_HZ.items())},
            "polling_physically_validated_values": sorted(
                data.POLLING_PHYSICALLY_VALIDATED_VALUES
            ),
        },
        "feature_registers": {
            str(number): {"name": name, "value_length": length, "writable": writable}
            for number, (name, length, writable) in sorted(data.FEATURE_REGISTERS.items())
        },
        "products": rows,
    }
    return json.dumps(document, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    root = Path(argv[1])
    if not (root / "crates" / "pproto").is_dir():
        print(f"{root} does not look like the Peripheral worktree root")
        return 2

    rows = _product_rows()
    rust_path = root / "crates" / "pproto" / "src" / "aula_bytech_catalog.rs"
    json_path = root / "data" / "devices" / "aula-bytech-catalog.json"
    rust_path.write_text(emit_rust(rows), encoding="utf-8", newline="\n")
    json_path.write_text(emit_json(rows), encoding="utf-8", newline="\n")
    print(f"wrote {rust_path} ({rust_path.stat().st_size} bytes)")
    print(f"wrote {json_path} ({json_path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
