"""Evidence levels, facts, and provenance data models."""

from enum import Enum, IntEnum
from typing import Optional, Any
from pydantic import BaseModel, Field
import datetime


class EvidenceLevel(IntEnum):
    """Hierarchy of provenance assurance."""
    LEVEL_1_METADATA = 1        # brand, model, product_url, driver_url, version, release date
    LEVEL_2_DEVICE_IDENTITY = 2 # VID, PID, manufacturer string, product string, usage page, usage, wired/wireless
    LEVEL_3_PROTOCOL_HINT = 3   # sdkModuleName, shared module, report size, report ID pattern, command names
    LEVEL_4_PROTOCOL_FACT = 4   # opcode, packet layout, response layout, codec semantics (candidate for review)
    LEVEL_5_HARDWARE_VERIFIED = 5 # Hardware tested in real device (never generated by crawler)


class SourceType(str, Enum):
    VENDOR_WEB = "vendor_web"
    VENDOR_PRODUCT = "vendor_product"
    VENDOR_DOWNLOAD = "vendor_download"
    VENDOR_SOFTWARE = "vendor_software"
    VENDOR_TECHNICAL = "vendor_technical"
    VENDOR_REGIONAL = "vendor_regional"
    WEB_CONFIGURATOR = "web_configurator"
    OFFICIAL_REPOSITORY = "official_repository"
    RETAILER = "retailer"
    DISTRIBUTOR = "distributor"
    OPEN_SOURCE = "open_source"
    COMMUNITY = "community"
    ARCHIVE = "archive"
    OTHER = "other"


class RawSource(BaseModel):
    url: str
    source_type: SourceType
    vendor: str
    retrieved_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    http_status: int = 200
    content_hash: Optional[str] = None
    etag: Optional[str] = None
    last_modified: Optional[str] = None


class RawArtifact(BaseModel):
    original_url: str
    final_url: Optional[str] = None
    filename: str
    content_type: Optional[str] = None
    size: int = 0
    sha256: Optional[str] = None
    etag: Optional[str] = None
    last_modified: Optional[str] = None
    normalized_url: Optional[str] = None
    downloaded_at: Optional[datetime.datetime] = None
    vendor: str
    software_version: Optional[str] = None
    related_products: list[str] = Field(default_factory=list)


class RawProduct(BaseModel):
    vendor: str
    raw_name: str
    canonical_name: Optional[str] = None
    category: Optional[str] = None  # keyboard, mouse, headset, keycap, switch, cable, accessory, other
    product_url: Optional[str] = None
    download_page_url: Optional[str] = None
    driver_url: Optional[str] = None
    web_configurator_url: Optional[str] = None
    software_version: Optional[str] = None
    release_date: Optional[str] = None
    image_url: Optional[str] = None
    connectivity: list[str] = Field(default_factory=list)  # wired, 2.4g, bluetooth
    extra_metadata: dict[str, Any] = Field(default_factory=dict)
    source_url: str = ""


class DeviceIdentifierFact(BaseModel):
    product_id: Optional[int] = None
    vid: int
    pid: int
    vid_hex: str
    pid_hex: str
    manufacturer_string: Optional[str] = None
    product_string: Optional[str] = None
    usage_page: Optional[int] = None
    usage: Optional[int] = None
    connection_type: Optional[str] = None
    source_id: Optional[int] = None
    artifact_sha256: Optional[str] = None
    evidence_level: EvidenceLevel = EvidenceLevel.LEVEL_2_DEVICE_IDENTITY
    confidence: float = 1.0


class ProtocolHintFact(BaseModel):
    product_id: Optional[int] = None
    hint_key: str
    hint_value: str
    source_id: Optional[int] = None
    artifact_sha256: Optional[str] = None
    evidence_level: EvidenceLevel = EvidenceLevel.LEVEL_3_PROTOCOL_HINT
    confidence: float = 0.8
    context: Optional[str] = None


class GenericFact(BaseModel):
    product_id: Optional[int] = None
    key: str
    value: str
    source_id: Optional[int] = None
    artifact_sha256: Optional[str] = None
    evidence_level: EvidenceLevel = EvidenceLevel.LEVEL_1_METADATA
    confidence: float = 1.0
    is_inference: bool = False
