# Generated by build_probe_sidecar.py at build time. Do not edit.
BUILD_COMMIT = "b95b006c71d5"
BUILD_DIRTY = False
BUILD_TIMESTAMP = 1787938512.3817515
PROBE_APP_VERSION = "0.3.0"
PROBE_ENGINE_VERSION = "0.3.0"
