# Generated by build_probe_sidecar.py at build time. Do not edit.
BUILD_COMMIT = "889830e2810e"
BUILD_DIRTY = True
BUILD_TIMESTAMP = 1787938341.0588243
PROBE_APP_VERSION = "0.3.0"
PROBE_ENGINE_VERSION = "0.3.0"
